### ISSUE TITLE
[BUG] Sprite and portrait revert to male in winter

### ISSUE THREAD

**Issue by Florian-Naud** [Onmyoujin/combined-girl-mod#9]
**Describe the bug**
Sprite and portrait revert to male in winter

**To Reproduce**
Just run a game with the game active. You need to be in winter to see the problem

**Expected behavior**
Either have the default sprite/portrait or use a custom sprite/portrait for winter

**Game Environment (please complete the following information):**
 - Stardew Valley Version: 1.6.4
 - SMAPI Version: 4.0.8
 - Content Patcher Version: 2.3.0
 - Combined Girl Mod Version: 1.6.5

**Additional context**
I can create a branch and do the fix myself if you can't do it.
To fix the issues, we can either map the winter sprite/portrait to the mod's general outfit OR use this mod: https://www.nexusmods.com/stardewvalley/mods/21500. 
The only downfall of the second method is that I can't find winter sprite/portrait for Willy and Wizard. And I'm not competent enough to make them

**Comment by Onmyoujin** [comment]
Florian-

Thank you for your report!  I was able to verify the bug you reported; it's common for all of the replacements since the artwork I've included in the mod has not been updated with the new winter sprites and portraits.  You are welcome to fork the project and submit a pull request with your changes (don't forget to update the various credits files to get credited for your work!).  I am recovering from eye surgery at the moment so I am not likely going to be able to start work on it myself for the next few weeks at a minimum.

**Comment by Florian-Naud** [comment]
Hello,

I hope you are well and that your eye surgery went fine.

I created the pull request for the easy and fast method. 
I will later add the winter outfit of RedK1rby. I want his agreement to use his assets. (even if he is in the credit for the beach outfit).  
I'll let you do the review and if it's good with you, you can publish it in nexusmods.

Good day to you and take care!
